### ISSUE TITLE
Accuracy returned by the prosdk-addons-matlab seems to be too bad. 

### ISSUE THREAD

**Issue by kurokida** [tobiipro/prosdk-addons-matlab#1]
I used the addons for a validation of the calibration, and noticed the accuracy for the both eyes was about 16 degree. I think this is a very large number, while my eye tracker (4c) seems to work very accurately.
I was making an program for an experiment of psychology using the SDK for Matlab. In this SDK the calibration result showed lines indicating the accuracy of the calibration, and the length of the lines was very short (i.e. very accurate). I don't think there was the bad accuracy of about 16 degree.
Could you tell me the reason why I got the large degree number as the accuracy?

**Comment by pedrotari7** [comment]
Hi @kurokida, that sounds really strange indeed. If possible, could you send me a mat file with the CalibrationValidationResult object and if possible another with the ScreenBasedCalibrationValidation object ? Because without more information is hard for me to guess what might be going wrong. Thanks

**Comment by kurokida** [comment]
Thank you for your kind reply. I attached a zip file including the mat file and a picture of the calibration result. Probably you will notice that the accuracy in the mat file is too bad for that in the picture. 
I also contacted the tobii support center about this issue, and received a mail in which it was written that the accuracy of 4c is not so good because it is a consumer model. But I do not think that it is true because the 4c seems to work accurately in my experiment. 

Please note that I modified your original code a little because the use of "round" is not supported in my Matlab version.

BEFORE
accuracy_left_eye = round(calib_validation.Angle(direction_target_left, direction_gaze_point_left), 3);

AFTER
accuracy_left_eye = round(calib_validation.Angle(direction_target_left, direction_gaze_point_left)*1000)/1000;

Regards,

[validationResult.zip](https://github.com/tobiipro/prosdk-addons-matlab/files/1878327/validationResult.zip)

**Comment by pedrotari7** [comment]
Thank you for the data, it was very helpful for debugging :)

Looking at your data:
![calibration_validation](https://user-images.githubusercontent.com/9287850/38359547-fa73506a-38c8-11e8-94dc-4ad30de2f22c.png)

It seems that during the calibration validation you are collecting data with the wrong x and y coordinates, they seem to be switched, the call should be `collect_data([x y])` and you seem to have sent `collect_data([y x])`.

Regarding the round issue, which version of Matlab didn't work as expected?

**Comment by kurokida** [comment]
Thank you for debugging and I apologize for my easy mistake. In accordance with your instructions I tried a calibration again and got the accuracy of about 0.3 degree! Very thanks!

The round issue is written here although in Japanese.
https://jp.mathworks.com/matlabcentral/answers/103483-
According to the page, for example
Y = round(pi,3)
This use is permitted after R2014b.

**Comment by pedrotari7** [comment]
No problem, thanks for the feedback!
